version: '3.8'

services:
    krakend:
        image: devopsfaith/krakend:1.4.1-alpine
        volumes:
            - ./krakend/:/etc/krakend/
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/__health" ]
            interval: 1m
            timeout: 10s
            retries: 3
            start_period: 40s
        ports:
            - "8080:8080"

    api_service_time:
        image: openresty/openresty:1.19.9.1-5-alpine-fat
        expose:
            - 8091
        ports:
            - "8091:8091"
        volumes:
            - ./nginx/time.nginx.conf:/etc/nginx/conf.d/time.nginx.conf

    api_service_weather:
        image: openresty/openresty:1.19.9.1-5-alpine-fat
        expose:
            - 8092
        ports:
            - "8092:8092"
        volumes:
            - ./nginx/weather.nginx.conf:/etc/nginx/conf.d/weather.nginx.conf

    keycloak_mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: keycloak
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: keycloak
        volumes:
            - keycloak-db-data:/var/lib/mysql:rw

    keycloak:
        image: jboss/keycloak:16.1.1
        environment:
            KEYCLOAK_USER: keycloak
            KEYCLOAK_PASSWORD: keycloak
            DB_VENDOR: MYSQL
            DB_ADDR: keycloak_mysql
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: keycloak
        command: ["-Djboss.http.port=8070"]
        ports:
            - "8070:8070"
        depends_on:
            - keycloak_mysql
volumes:
    keycloak-db-data:
        driver: local
